version: "3.9"

volumes:
    postgres_data:

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 8025:8025

  base: &base
    build: .

  web:
    << : *base
    command: python manage.py runserver 0.0.0.0:8000
#    command: commands.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailhog

  test:
    << : *base
    command: pytest
